### ISSUE TITLE
Grain initialization for complex parts

### ISSUE THREAD

**Issue by jwwtc** [LLNL/ExaCA#229]
@MattRolchigo Hello. For a part similar to the images, or even a more complex part, does it make sense to initialize substrate grains where there is a lack of thermal data? Wouldn't it be better to skip the initialization above a certain height? Thanks in advance.

<img src="https://github.com/LLNL/ExaCA/assets/69092842/86d1f6a8-9933-458f-b698-c21fbd860b94" width="45%" align="left" alt="TwoBlock_design">
<img src="https://github.com/LLNL/ExaCA/assets/69092842/595b18c6-d7c6-4bae-b714-425c79fa6626" width="45%" align="right" alt="TwoBlock">

**Comment by MattRolchigo** [comment]
@jwwtc , this is a good question, there are two ways of handling this region in ExaCA:

The first is extending the substrate through the layers, so that the "baseplate" microstructure is continuous. This has the effect of allowing new grains from the edges of the part to advance inward, and allows a single variable (substrate grain size) to control the size of these new grains in both the "layer 0" boundary condition and the "layer n" boundary condition. This can be done by setting `inputdata["Substrate"]["ExtendSubstrateThroughPower"]` to `true` in the input file. This has the downside of making substrate generation take longer, and I later came up with a better way of handling the edges of the thermal data for each layer.

The second (and in my opinion, better) way of handling this is to set the variable`["Substrate"]["PowderDensity"]` in the input file - this sets a special kind of nucleation site at these edges, where new grains nucleate once the corresponding cell is undercooled. Similar to the nucleation density, this is given as a value normalized by 10^12 /m^3 (i.e., a value of 1 will set the density of these powder surface sites to 10^12). If, for a given problem, you don't believe that new grain nucleation/growth inward from powder particles for powder bed fusion is significant at these edges, you can set this to zero.

**Comment by jwwtc** [comment]
Surprisingly, I'm observing extremely similar results (as seen in the cross-sectional images) when setting the `["Substrate"]["PowderDensity"]` parameter to either `0` or `1000` in the input file. Possibly, the difference would be apparent in lower mesh/cell sizes? I could attach the temperature file as well, if the issue is not apparent from these.

### Cross-sections

#### `["PowderDensity"]=0`

![TwoBlock_0](https://github.com/LLNL/ExaCA/assets/69092842/6a864c91-e383-421e-b9fe-e042cb2340ab)

#### `["PowderDensity"]=1000`

![TwoBlock_1000](https://github.com/LLNL/ExaCA/assets/69092842/16bbd0b2-9345-40f8-b019-4598ca2f500f)

### Input File

```json
{
    "SimulationType": "R",
    "MaterialFileName": "[path]",
    "GrainOrientationFile": "[path]",
    "RandomSeed": 0.0,
    "Domain": {
        "CellSize": 10,
        "TimeStep": 1,
        "NumberOfLayers": 9,
        "LayerOffset": 0
    },
    "Nucleation": {
       "Density": 0,
       "MeanUndercooling": 5,
       "StDev": 0.5
    },
    "TemperatureData": {
        "HeatTransferCellSize": 10,
        "LayerwiseTempRead": false,
        "TemperatureFiles": ["[path]"]
    },
    "Substrate": {
       "MeanSize": 8,
       "PowderDensity": 0
    },
    "Printing": {
        "PathToOutput": "[path]",
        "OutputFile": "TwoBlock",
        "PrintBinary": false,
        "PrintExaConstitSize": 0,
        "PrintFieldsInit": [],
        "PrintFieldsFinal": ["GrainID", "LayerID", "GrainMisorientation"],
        "PrintIntermediateOutput": {
            "Frequency": 0,
            "PrintIdleFrames": false
        }
    }
}
```

**Comment by MattRolchigo** [comment]
Hmm... can you try using the "slice" tool in Paraview and attaching images of the same slice from each? It could be due to Paraview blurring the differences together, but if the pixel-by-pixel powder grain structure is exactly the same, there could be a bug in the initialization routine. For "unassigned" cells (GrainID = 0), a filler misorientation value of 200 should be printed, while the other cells all have misorientations between 0 and 62 or so

**Comment by jwwtc** [comment]
I used the slice tool for both cross-sections that bisect the part. The powder structure indeed seems to be exactly the same. Thus, the most probable issue has to do with initialization? Also, these are also produced with the latest version of the software.

**Comment by MattRolchigo** [comment]
Ah, I see what might be happening. In your input file, you set `LayerHeight` to 0, presumably because each layer's temperature coordinates are already offset by the appropriate amount in the Z direction. But in the subroutine where the powder grain ID are assigned, `LayerHeight` is used to assign the bounds of the powder layer - so setting `LayerHeight` to 0 causes the power grain structure to go uninitialized (which must be defaulting to some random positive numbers). I'll have to fix that

**Comment by jwwtc** [comment]
Okay, I'll keep up with the updates to start using this feature. Thanks!

**Comment by MattRolchigo** [comment]
By the way, ExaCA's default behavior is to have the first layer ("layer 0") scan over a baseplate without powder. Is that okay, or would you prefer a first layer that includes powder as well? `["Substrate"]["PowderFirstLayer"]` to `true` will allow you to do that - though with `LayerHeight` = 0, I'd also need to know the Z coordinate corresponding to the top of your baseplate in the first layer

**Comment by MattRolchigo** [comment]
@jwwtc #234 should hopefully address your issue. Instead of setting `["Substrate"]["PowderFirstLayer"]`, you can simply set `["Substrate"]["BaseplateTopZ"]` in your input file to the value (in meters) of the Z coordinate of the top of your baseplate. Everything above this coordinate will be initialized as powder using the bounds of the temperature data

**Comment by MattRolchigo** [comment]
I think I understand what you mean. I do have the option to set `BaseplateThroughPowder = true` in the code instead of setting `PowderDensity` in the `Substrate` portion of the input file - but the grain size in the unmelted powder layer will be the same as that of the baseplate. The powder density variable essentially considers the unmelted powder-liquid interface as a separate set of nucleation sites, which all nucleate at an undercooling of 0. It's a bit counterintuitive but I don't think making these powder grain sites larger will significantly change the results, despite the fact that the powder-liquid contact is certainly more than one cell width wide. My reasoning for this that since the powder grains are primarily competing with other powder grains in these regions of the melt pool, they'll naturally fill the intermediate space at the interface based on their density once they cool below the liquidus.

**Comment by jwwtc** [comment]
Interesting. If this reasoning makes sense (and I believe it does), we have control over the initialization and, thus, the penetrating growth at the sides. Thanks again.
